### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'requirements/main.txt'

### ISSUE THREAD

**Issue by rpanai** [facebookincubator/submitit#16]
I'm trying to build a conda-forge package out of this but when I try to build the recipe with `conda skeleton pypi submitit` I have the following error
```
FileNotFoundError: [Errno 2] No such file or directory: 'requirements/main.txt'
$PYTHONPATH = /tmp/tmpgmz9b72rconda_skeleton_submitit-1.1.0.tar.gz/submitit-1.1.0
```

**Comment by gwenzek** [comment]
I don't think the requirements.txt files are part of the release. Should it be the case ?

I've never created a conda package, so I'm not sure how it works.

**Comment by jrapin** [comment]
They should be in the tarball, I've had the same issue with nevergrad:
https://github.com/facebookresearch/nevergrad/issues/54
with a followup because the initial solution was bad:
https://github.com/facebookresearch/nevergrad/issues/259
Basically, they should be explicitely mentioned in a MANIFEST.in file in the root directory of the package (see second PR)

**Comment by gwenzek** [comment]
I think the issue was on my side, I did a release with an old version of setuptools.
It seems that newer version does correctly include the requirements automatically.

You can check the archive at https://files.pythonhosted.org/packages/3d/7a/af94dc7bb279f84346419b1b0a036479878fe97b0e2913369f18d4bf5880/submitit-1.1.1.tar.gz

Also running the conda command works for me now, and produce the following skeleton:

```
{% set name = "submitit" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "d7ba4d0301b43c0be09d53dd0a3d646a92c1f0fba3f546e783d9dc2361b8dfce"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - cloudpickle >=1.2.1
    - pip
    - python
    - typing_extensions >=3.7.4.2
  run:
    - cloudpickle >=1.2.1
    - python
    - typing_extensions >=3.7.4.2

test:
  imports:
    - submitit
    - submitit.auto
    - submitit.core
    - submitit.local
    - submitit.slurm

about:
  home: "The package home page"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "Python 3.6+ toolbox for submitting jobs to Slurm"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
```
