### ISSUE TITLE
No user code logging output is shown in logs

### ISSUE THREAD

**Issue by fleimgruber** [facebookincubator/submitit#1721]
Summary: I am not seeing expected logging info in SLURM log files.

Given this submitit script:

```python
import submitit

from src.the_module.the_func

with open("log.yml", "rt", encoding="utf-8") as logconfig:
    config = yaml.load(logconfig.read(), Loader=yaml.FullLoader)
logging.config.dictConfig(config)

executor = submitit.AutoExecutor(folder="log_test")

executor.update_parameters(timeout_min=1, slurm_partition="dev")
job = executor.submit(the_func, the, args)

output = job.result()
```

the logging in `src.the_module`:

```python
LOGGER = logging.getLogger(__name__)
...
LOGGER.info(...)
...
```

the logging config in "log.yml":

```yaml
version: 1
...
loggers:
  src.the_module:
    level: INFO
    handlers: [console, file]
  the_module:
    level: INFO
    handlers: [console, file]
```

I do not see `the_module` INFO lines in "log_test/JOBID_0_log.out", only the default submitit INFO log lines and the job stdout. Is this even supposed to work that way or does logging have to be configured some other way in submitit?
